server:
  port: 8003


#应用名称
spring:
  application:
    name: dcloud-link

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.86.147:8848
        username: nacos
        password: 2018LYW@#$


  # shardingSphere相关配置
  shardingsphere:
    # 数据源配置
    datasource:
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://47.100.86.147:3306/dcloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        username: root
        password: 2018LYW@#$
    # 打印执行的数据库以及语句
    props:
      sql:
        show: true

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

