server:
  port: 8004


#应用名称
spring:
  application:
    name: dcloud-shop

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.86.147:8848
        username: nacos
        password: 2018LYW@#$


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

